### ISSUE TITLE
FxA Icon doesn't follow UI standard color when in dark theme

### ISSUE THREAD

**Issue by poubina** [mozilla/fxa-discoverability-shield-study#35]
[Affected versions]:
Firefox Nightly 66.0a1 and above

[Affected Platforms]:
All Linux

[Prerequisites]:
Add-on installed
A valid User email connected to FxA

[Steps to reproduce]:
1. Go to about:addons -> Themes
2. Enable "Dark" theme

[Expected result]:
FxA icon must follow UI color standards.

[Actual result]:
FxA icon is not following UI color standards.

[Notes]:
Please find screenshot attached.

![darktheme](https://user-images.githubusercontent.com/44272078/51688758-06419580-1fd4-11e9-8e16-483b109517eb.png)

**Comment by vbudhram** [comment]
@LucianaQueirolo Thanks for find, I'll update the icon to photo color.

**Comment by SoftVision-CarmenFat** [comment]
This issue is still reproducible on Windows 10 x64 and Mac OS 10.14.2.

![icon](https://user-images.githubusercontent.com/26000308/51839483-01e9e500-2312-11e9-85a4-19a3b5538475.png)

**Comment by SoftVision-CarmenFat** [comment]
- I have verified that the issue is no longer reproducible on Firefox Unbranded Beta 66.0b3 using Windows 10 x64 and Mac 10.14.2.
- The avatar icon is now visible when the user enables  Dark Theme.
