### ISSUE TITLE
Vertical line (light grey) in wrong position

### ISSUE THREAD

**Issue by poubina** [mozilla/fxa-discoverability-shield-study#36]
[Affected versions]:
Firefox Nightly 66.0a1 and above

[Affected Platforms]:
All Linux

[Prerequisites]:
Add-on installed

[Steps to reproduce]:
Open browser 
See behavior

[Expected result]:
The must be a vertical line (light grey) at the left of avatar icon according to specs.

[Actual result]:
There is a vertical line (light grey) at the right of avatar icon.

[Notes]:
Please find screenshot attached.

![linewrongposition](https://user-images.githubusercontent.com/44272078/51694192-0d21d580-1fdf-11e9-8973-849d4834240d.png)

**Comment by vbudhram** [comment]
@poubina Looks like our UX has not been updated yet. For this phase it is ok to have it on the left of the grey line. 

I'll try to get our designer (cc @ryanfeeley ) to make clear distinction for phase 1 in design docs.

**Comment by ryanfeeley** [comment]
Vijay is right. Product compromised on this as the extension API does not support easily moving that line. However, it's still a goal for the longer term design so I will close this issue. Please make a note that this is wrong in the mockup.
