### ISSUE TITLE
Add-on is not persistent after updating the browser.

### ISSUE THREAD

**Issue by LucianaQueirolo** [mozilla/fxa-discoverability-shield-study#37]
[Affected versions]:
Firefox Nightly 65

[Affected Platforms]:
Mac OS

[Prerequisites]:
FxA verified account.

[Steps to reproduce]:
1. Open the older version of the browser.
2. Install add-on on about:debugging.
3. Update the browser version.
4. Check on browser tool bar for the avatar icon.
5. Check on about:debugging for the add-on.

[Expected result]:
Shield study add-on is still installed.

[Actual result]:
Add-on is not persistent after updating the browser.

[Notes]:
Please find screenshot attached.
![fxa browser apdate](https://user-images.githubusercontent.com/44404741/51695710-77884500-1fe2-11e9-8907-609340312ce5.gif)

**Comment by vbudhram** [comment]
@LucianaQueirolo I believe this should be fixed when installing the signed version of the add-on at https://bugzilla.mozilla.org/show_bug.cgi?id=1522598? Mind giving it a try with that?
