### ISSUE TITLE
Add-on is not re-enabled after Safe mode.

### ISSUE THREAD

**Issue by LucianaQueirolo** [mozilla/fxa-discoverability-shield-study#38]
[Affected versions]:
Firefox Nightly 66.0a1 and above

[Affected Platforms]:
Mac OS

[Prerequisites]:
Add-on installed
A verified User email connected to FxA

[Steps to reproduce]:
1. Navigate to "about:support" page
2. Click the "Restart with Add-ons Disabled..." button.
3. The addon is disabled.
4. Restart the browser and verify if the add-on is re-enabled.

[Expected result]:
Shield study add-on is still installed.

[Actual result]:
Add-on is not re-enabled after Safe mode.

[Notes]:
Please find screenshot attached.

**Comment by vbudhram** [comment]
@LucianaQueirolo I suspect this might have something to do with it being loaded as a temporary addon. They don't persist on restarts. Hopefully a signed extension will fix this.

**Comment by poubina** [comment]
We tried with fxa-browser-discoverability@shield.mozilla.org-1.0.0-signed-test xpi from https://bugzilla.mozilla.org/show_bug.cgi?id=1522598 in LINUX and it continues failing.

**Comment by LucianaQueirolo** [comment]
Tested on new version 1.0.1 this issue no longer occurs.
