### ISSUE TITLE
Placeholder remains displayed when drag&dropping the zip file on about:addons (group control)

### ISSUE THREAD

**Issue by poubina** [mozilla/fxa-discoverability-shield-study#40]
[Affected versions]:
Firefox Nightly 66.0 and above

[Affected Platforms]:
All Linux

[Prerequisites]:
Nightly 66 version installed
Have the latest "FxA" zip. file saved to drive.
Have a new Profile created.

[Steps to reproduce]:
1. Go to "about:config" page and set "xpinstall.signatures.required" to "false"
2. Set preferences on "about:config" page: "extensions.fxa-browser-discoverability_shield_mozilla_org.test.variationName" (string type) to "control" and "extensions.fxa-browser-discoverability_shield_mozilla_org.test.expired" (boolean type) to "false"
3. Go to "about:addons" > Extensions and drag and drop the zip file.
4. See behavior.

[Expected result]:
The avatar icon is not displayed in the browser toolbar.

[Actual result]:
The avatar icon is not displayed in the browser toolbar, but the placeholder remains displayed with no action when clicking on "Turn on Sync...". **This issue doesn't happen if you "Load Temporary Add-on.." from about:debugging**

[Notes]:
Please find screenshot attached.

![draganddropaddons](https://user-images.githubusercontent.com/44272078/51706652-e6bf6280-1ffd-11e9-8361-b0dc34caefc3.png)

**Comment by vbudhram** [comment]
@SoftVision-CosminMuntean Marking this as closed because the new test [process](https://github.com/mozilla/fxa-discoverability-shield-study/blob/master/docs/TESTPLAN.md#install-the-add-on-and-enroll-in-the-study) uses signed extension with `xpinstall.signatures.dev-root=true`.

Ref https://bugzilla.mozilla.org/show_bug.cgi?id=1522598#c4
