### ISSUE TITLE
Telemetry - signinComplete - hasAvatar = false although user has avatar set

### ISSUE THREAD

**Issue by poubina** [mozilla/fxa-discoverability-shield-study#53]
[Affected versions]:
Firefox Nightly 66.0 and above

[Affected Platforms]:
All Linux

[Prerequisites]:
Have the latest Firefox 66.0b2-candidates build installed.
Have the add-on installed.
Have a valid FxA account that has a avatar set.

[Steps to reproduce]:
1. Click the "avatar"
2. Click on "Turn on Sync"
3. Login with a valid account that has an avatar set
4. Navigate to "about:telemetry" page (refresh the page if it was previously loaded).
5. Click the "shield-study-addon" button -> Select the "Archived ping data" option and click the dropdown button from the "Ping" section.
6. Click the latest sent ping and check it

[Expected result]:
The field "hasAvatar" is set to "true".

[Actual result]:
The field "hasAvatar" is set to "false".

[Notes]:
Please find screenshot attached.

![hasavatarfalse](https://user-images.githubusercontent.com/44272078/51764480-0f099880-20b4-11e9-9835-85efe32ba48f.png)

**Comment by LucianaQueirolo** [comment]
This issue also occurs on Mac OS.

**Comment by vbudhram** [comment]
Spoke with @irrationalagent and he said that this shouldn't be a problem since he can filter out on the data side, closing.
