### ISSUE TITLE
Telemetry - signoutComplete - hasAvatar = false although user has avatar set 

### ISSUE THREAD

**Issue by poubina** [mozilla/fxa-discoverability-shield-study#54]
[Affected versions]:
Firefox Nightly 66.0 and above

[Affected Platforms]:
All Linux

[Prerequisites]:
Have the latest Firefox 66.0b2-candidates build installed.
Have the add-on installed.
Have a valid FxA account that has a avatar set.

[Steps to reproduce]:
Click the "avatar"
Click the "Sync Preferences" option from the doorhanger.
Logout from a valid account that has an avatar set
Navigate to "about:telemetry" page (refresh the page if it was previously loaded).
Click the "shield-study-addon" button -> Select the "Archived ping data" option and click the dropdown button from the "Ping" section.
Click the latest sent ping and check it

[Expected result]:
The field "hasAvatar" is set to "true".

[Actual result]:
The field "hasAvatar" is set to "false".

[Notes]:
Please find screenshot attached.

![hasavatarfalsedisconnect](https://user-images.githubusercontent.com/44272078/51766317-036ca080-20b9-11e9-9bfd-3bafe164516e.png)

**Comment by vbudhram** [comment]
@poubina Looked into this and the way we get the avatar is to check the current logged in user. When you log out, there is no current logged in user and therefore would report avatar as false.

We will have to pass the original logged in user to telemetry.

**Comment by vbudhram** [comment]
Spoke with @irrationalagent and he said that this shouldn't be a problem since he can filter out on the data side, closing.
