### ISSUE TITLE
FxA add-on - Chosen selections are not saved on account preferences

### ISSUE THREAD

**Issue by LucianaQueirolo** [mozilla/fxa-discoverability-shield-study#55]
[Affected versions]:
Firefox Nightly 66.0a1 and above

[Affected Platforms]:
Windows 10

[Prerequisites]:
Add-on installed
Treatment branch set.
new account created, not verified.

[Steps to reproduce]:
1. Complete the email, password and age fields.
2. Choose some of the check boxes. and Save.
3. Verify the email account.
4. Go to Preferences.
5. Check the Sync settings.

[Expected result]:
Chosen selections are saved on account preferences

[Actual result]:
Chosen selections are not saved on account preferences

[Notes]:
Please find screenshot attached.
![captura de pantalla 14](https://user-images.githubusercontent.com/44404741/51768828-2f3f5480-20c0-11e9-99e6-36937092e615.png)
![captura de pantalla 15](https://user-images.githubusercontent.com/44404741/51768842-36666280-20c0-11e9-81ed-227748879a0e.png)

**Comment by vbudhram** [comment]
Tested this with unsigned version 1.0.1 from https://bugzilla.mozilla.org/show_bug.cgi?id=1522598 and I was not able to reproduce. We should try to retest with signed version when it is available.

**Comment by LucianaQueirolo** [comment]
Tested with version 1.0.1 as suggested, this issue no longer occurs.
