### ISSUE TITLE
Setting the system date to 30 days after doesn't uninstall the addon

### ISSUE THREAD

**Issue by LucianaQueirolo** [mozilla/fxa-discoverability-shield-study#57]
[Affected versions]:
Firefox Nightly 66.0a1 and above

[Affected Platforms]:
Windows 10
Mac OS

[Prerequisites]:
Shield study add-on is installed.
The following pref is set: -"extensions.fxa-browser-discoverability_shield_mozilla_org.test.variationName" to "treatment" "extensions.fxa-browser-discoverability_shield_mozilla_org.test.expired to "false"
extensions.legacy.enabled is set to true
You are in the "treatment" branch.
Connected with verified account.

[Steps to reproduce]:
1. Set the system date to 30 days after the current date.
2. Open the browser with the profile from prerequisites and navigate to "about:support" page
3. Check that the add-on is uninstalled.

[Expected result]:
The add-on is no longer displayed.

[Actual result]:
Setting the system date to 30 days after doesn't uninstall the addon

[Notes]:
Please find screenshot attached.
![fecha y hora](https://user-images.githubusercontent.com/44404741/51836369-05b04400-22df-11e9-9873-07d11a5997ce.PNG)

**Comment by vbudhram** [comment]
@LucianaQueirolo I tested this with windows 10 and it was able to uninstall itself. Here are my STR

[Prerequisites]:
Use Unbranded Firefox from https://wiki.mozilla.org/Add-ons/Extension_Signing#Unbranded_Builds

The following pref is set: 
`extensions.fxa-browser-discoverability_shield_mozilla_org.test.variationName=treatment`
`extensions.legacy.enabled=true`
`xpinstall.signatures.dev-root=true`

Shield study add-on is installed from https://bugzilla.mozilla.org/attachment.cgi?id=9039229

You are in the "treatment" branch.
Connected with verified account.

[Steps]:
1. Set time ahead 31 days
2. Restart browser

Some notes:

I suspect that setting `extensions.fxa-browser-discoverability_shield_mozilla_org.test.expired=false` might override any system time setting. I would remove that config.

**Comment by LucianaQueirolo** [comment]
Tried as suggested, the issue no longer occurs.
