### ISSUE TITLE
V2 - Shield study ID - "about:support" page is wrong 

### ISSUE THREAD

**Issue by poubina** [mozilla/fxa-discoverability-shield-study#64]
[Affected versions]:

* Firefox Nightly 65.0

[Affected Platforms]:

* All Linux

[Prerequisites]:

* Browser version is installed and opened.
* Shield study add-on is installed.
* The following pref is set: -"extensions.fxa-browser-discoverability_mozilla_org.test.variationName" to "treatment" "extensions.fxa-browser-discoverability_mozilla_org.test.expired to "false"
extensions.legacy.enabled is set to true
* You are in the "treatment" branch.

[Steps to reproduce]:

1. Navigate to "about:support" page.
2. Scroll down to "Extensions" section and observe the add-on's ID.

[Expected result]:

* The add-on's ID ends in "@shield.mozilla.org".

[Actual result]:

* The add-on's ID ends in "@mozilla.org".

[Notes]:

* Please see the screencast attached.

![unix](https://user-images.githubusercontent.com/44272078/52563997-b0e1f280-2de1-11e9-9bda-5ec9b0cfc856.png)

**Comment by vbudhram** [comment]
@poubina Spoke with the folks in the #shield channel and they said that normally shield addons have `  @shield.mozilla.org`, it was ok for this extension not to have it since the change fixes https://github.com/mozilla/fxa-discoverability-shield-study/issues/35.

**Comment by poubina** [comment]
@vbudhram ok, if you tell so, i will add the label "won't fix".
