### ISSUE TITLE
V2 - Design - missing ">" in option "Send tab to device" 

### ISSUE THREAD

**Issue by poubina** [mozilla/fxa-discoverability-shield-study#65]
[Affected versions]:

* Firefox Nightly 65.0

[Affected Platforms]:

* All Linux

[Prerequisites]:

* Browser version is installed and opened.
* Shield study add-on is installed.
* The following pref is set: -"extensions.fxa-browser-discoverability_mozilla_org.test.variationName" to "treatment2" "extensions.fxa-browser-discoverability_mozilla_org.test.expired to "false"
  extensions.legacy.enabled is set to true
* You are in the "treatment2" branch.

[Steps to reproduce]:

1. Click on avatar icon and doorhanger will be displayed.
2. Observe options design.

[Expected result]:

* There is a ">" at the end of "Send to Device" option.

[Actual result]:

* There isn't a  ">" at the end of "Send to Device" option..

[Notes]:

* Please see the screencast attached.

![sendtabtodevice_expanded](https://user-images.githubusercontent.com/44272078/52580009-2bbd0480-2e06-11e9-85e8-72a46259cf82.png)

![sendtabtodevice_withavatar](https://user-images.githubusercontent.com/44272078/52580025-337ca900-2e06-11e9-8dd9-874b1d84326e.png)

![sendtabtodevice_noavatar](https://user-images.githubusercontent.com/44272078/52580031-37103000-2e06-11e9-8bd7-7c7ac6e430a0.png)

**Comment by vbudhram** [comment]
@LucianaQueirolo Unfortunately, this isn't a bug, in the V2 version clicking the link only opens a new tab to a blog.
