### ISSUE TITLE
Implement shield study metrics

### ISSUE THREAD

**Issue by vbudhram** [mozilla/fxa-discoverability-shield-study#7]
Per https://docs.google.com/document/d/129HzVoufID4S2HRKMivXNW6BvlR6lYMa7Nyg-D-ZenA/edit, this extension should be setup as a shield study.

* What are the branches of the study?
  * Control: no change.
  * Treatment: install an add-on that can expose FxA/Sync in the top level navigation.
* What percentage of users do you want in each branch? 
  * 5% for control
  * 5% for treatment
* What Channels and locales do you intend to ship to? 
  * Channel: Release
  * Locale: EN-*
* Log telemetry
  * User clicks avatar toolbar icon
  * User clicks sign-in in popup window
    * How many times they signed in
  * User successfully sign-in
    * How many times they signed out

**Comment by vbudhram** [comment]
@irrationalagent Please feel free to update anything I might be missing.

**Comment by irrationalagent** [comment]
yea, I'll try to come up with a more-or-less complete taxonomy for this tomorrow are f[eeley's recent designs here](https://mozilla.invisionapp.com/share/85PSXVZAKGY#/screens/339003076_Artboard) still good to go by?

**Comment by irrationalagent** [comment]
@vbudhram @philbooth FYI, assuming this is going to ship as an addon, [this is the API](https://firefox-source-docs.mozilla.org/toolkit/components/telemetry/telemetry/collection/events.html#the-api) to use to record the telemetry events

**Comment by irrationalagent** [comment]
Actually, what I wrote above may not be true -> looks like shield does something custom with events, investigating...
