### ISSUE TITLE
V2 - Survey - when on control or treatment, add-on is displaying the wrong survey (treatment2 survey)

### ISSUE THREAD

**Issue by poubina** [mozilla/fxa-discoverability-shield-study#71]
[Affected versions]:

* Firefox Nightly 65.0b9

[Affected Platforms]:

* All Linux

[Prerequisites]:

* Browser version is installed and opened.
* Shield study add-on version 2.0.1 is installed.
* The following pref (extensions.fxa-browser-discoverability_mozilla_org.test.variationName) is set to either "control" or "treatment". extensions.fxa-browser-discoverability_mozilla_org.test.expired set to false.

[Steps to reproduce]:

1. Change system date to current date +30 days.
2. Open browser with the profile of prerequisites.
3. Observe the survey page that will open in a new tab.

[Expected result]:

* Survey page for "control" is https://qsurvey.mozilla.com/s3/Avatar-Experiment?reason=expired
* Survey page for "treatment" is https://qsurvey.mozilla.com/s3/Avatar-Experiment?reason=expired

[Actual result]:

* Survey page for "control" is https://qsurvey.mozilla.com/s3/Avatar-Experiment-P2?reason=expired
* Survey page for "treatment" is https://qsurvey.mozilla.com/s3/Avatar-Experiment-P2?reason=expired
* For "control" and "treatment", the addon is displaying the "treatment2" survey page.

[Notes]:

N/A.

**Comment by vbudhram** [comment]
@poubina Looks like this is an error in our test plan doc, which should be fixed in https://github.com/mozilla/fxa-discoverability-shield-study/pull/73. All survey links should be pointing to the `Avatar-Experiment-P2` version.

**Comment by poubina** [comment]
@vbudhram but Avatar-Experiment-P2 version asks about firefox send tabs (Were you aware that Firefox allowed you to send tabs you have open from this computer to other devices you own?) and there is no send tabs option on control and treatment branches for the user. Are you sure ?

**Comment by vbudhram** [comment]
@poubina Yea, the survey will be the same for all the variations. Users in `control` and `treatment` should hopefully answer No more times than the `treatment2` users.
