### ISSUE TITLE
V2 - The addon is wrongly displayed on the about:addons page

### ISSUE THREAD

**Issue by poubina** [mozilla/fxa-discoverability-shield-study#74]
[Affected versions]:
Firefox 65.0b9

[Affected Platforms]:
All Linux

[Prerequisites]:
The FxA addon fxa-browser-discoverability@mozilla.org-2.0.3-signed-testing.xpi is installed.

[Steps to reproduce]:
Open the browser with the profile from prerequisites.
Navigate to about:addons and observe the "Extensions" section.

[Expected result]:
The addon is not displayed in the about:addons page.

[Actual result]:
The addon is displayed.

[Additional Notes]:
Please see [mozilla/side-view#385](https://github.com/mozilla/side-view/issues/385)

![screenshot from 2019-02-14 17-48-05](https://user-images.githubusercontent.com/44272078/52816781-c6287c80-3080-11e9-9820-ce57002e2730.png)

**Comment by vbudhram** [comment]
This is strange, nothing has changed since this was fixed in https://github.com/mozilla/fxa-discoverability-shield-study/issues/48, I updated the manifest file to have `hidden:true`.

Also, currently V1 has the same behavior in current unbranded Firefox 64+. I wonder if anything has landed that might have changed this behavior.

**Comment by vbudhram** [comment]
@poubina Looked into this a bit more. I think you have to have the config `xpinstall.signatures.dev-root=true` set. 

This allows Firefox to properly install the signed test add-on, which should fix the issue above. Ref: https://github.com/mozilla/fxa-discoverability-shield-study/blob/master/docs/TESTPLAN.md#install-the-add-on-and-enroll-in-the-study.

**Comment by poubina** [comment]
@vbudhram you're right. verified and working fine. closing issue.
